<a href="https://colab.research.google.com/github/GGMmattos/Machine-Learning-And-Data-Science/blob/main/Regress%C3%A3o_Logistica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regressão Logistica

In [36]:
from sklearn.linear_model import LogisticRegression

In [28]:
import numpy as np

In [29]:
import pickle
with open('risco_credito.pkl','rb') as f:
  X_risco_credito, y_risco_credito = pickle.load(f)

In [30]:
X_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

classe


Historia de credito -  Dívida - Garantia -  Renda

In [31]:
y_risco_credito # 2, 7, 11  tais arquivos serão excluidos

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [32]:
X_risco_credito = np.delete(X_risco_credito, [2, 7, 11], axis = 0) #axis = 0 (apagar linha), axis = 1(apagar coluna)


In [33]:
y_risco_credito = np.delete(y_risco_credito, [2, 7, 11], axis = 0)

Verificando o que foi deletado

In [34]:
X_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [35]:
y_risco_credito

array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'alto', 'baixo', 'baixo',
       'alto', 'baixo', 'alto'], dtype=object)

Treinamento

In [39]:
logistic_risco_credito = LogisticRegression(random_state = 1)
logistic_risco_credito.fit(X_risco_credito, y_risco_credito)

LogisticRegression(random_state=1)

b0

In [40]:
logistic_risco_credito.intercept_

array([-0.80828993])

Para casa atributo previsor b1,b2,b3,b4

In [42]:
logistic_risco_credito.coef_

array([[-0.76704533,  0.23906678, -0.47976059,  1.12186218]])

previsão

In [43]:
previsoes1 = logistic_risco_credito.predict([[0,0,1,2],[2,0,0,0]])

In [45]:
previsoes1

array(['baixo', 'alto'], dtype=object)